apiVersion: v1
kind: Service

metadata:
  name: grpc-server-service
  namespace: target-services
  labels:
    app: grpc-server

spec:
  type: ClusterIP
  selector:
    app: grpc-server

  ports:
    - name: grpc
      port: 60065
      targetPort: 60065
