apiVersion: v1
kind: Service
metadata:
  name: cs-ml-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: cs-model
spec:
  type: ClusterIP
  selector:
    app: cs-model
  ports:
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cs-model-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app: cs-model
    release: prometheus  # Important: This label tells Prometheus to pick it up
spec:
  selector:
    matchLabels:
      app: cs-model
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
