apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cs-model
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-cs-model
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-cs-model
  ports:
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: metrics
