apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cs-model
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cs-model
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cs-model
    spec:
      containers:
      - name: cs-model
        # Image is built from values.yaml
        image: "{{ .Values.pythonApp.image }}:{{ .Values.pythonApp.tag }}"
        imagePullPolicy: IfNotPresent
        command: ["python", "cs_model_service.py"]
        ports:
        - containerPort: 9001
          name: metrics
          protocol: TCP
        envFrom:
        - configMapRef:
            # References the name of the ConfigMap created above
            name: {{ .Release.Name }}-service-urls
