# This is your single source of truth for all variables

# Define all service connection details here
services:
  alertmanager:
    host: "prometheus-kube-prometheus-alertmanager.monitoring.svc.cluster.local"
    port: "9093"
    extras: "/api/v2/alerts"
  prometheus:
    host: "prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local"
    port: "9090"
  grafana:
    host: "prometheus-grafana.monitoring.svc.cluster.local"
    port: "3000"
  loki:
    host: "loki.monitoring.svc.cluster.local"
    port: "3100"

  

csModel:
  enabled: true
  image: chandrashekar316/capstone:cs_model
  deployment:
    name: cs-model-deployment  
  service:
    name: cs-model-service
    port: 9001

grpcServer:
  enabled: true
  image: chandrashekar316/capstone:grpc_server
  deployment:
    name: grpc-server-deployment
  service:
    name: grpc-server-service
    port: 60065

grpcClient:
  enabled: true
  image: chandrashekar316/capstone:grpc_client
  deployment:
    name: grpc-client-deployment

